services:
  postgres:
    image: postgres:16-alpine
    container_name: oficina-postgres
    environment:
      POSTGRES_DB: oficina_db
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: oficina
    ports:
      - "5432:5432"
    volumes:
      - oficina_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oficina -d oficina_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: oficina-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/oficina_db
      SPRING_DATASOURCE_USERNAME: oficina
      SPRING_DATASOURCE_PASSWORD: oficina
      APP_ADMIN_DEFAULT_USERNAME: admin
      APP_ADMIN_DEFAULT_PASSWORD: admin123
      APP_JWT_SECRET: awssecretpostech-oficina-fiap-2026
    ports:
      - "8080:8080"

volumes:
  oficina_postgres_data:
